### ISSUE TITLE
Importing it as a module

### ISSUE THREAD

**Issue by threatlead** [armbues/ioc-parser#13]
* ioc-parser didn't worked, as python doesn't like "-" (_dash_) in import statement
* Default setting of **patterns_ini** would be nice, not requiring user of module to pass it unnecessarily and override only if required [LINE #84]
* Ability to return python data structure (list, dict) along with csv/json/etc. currently supported

**Comment by armbues** [comment]
Three commits from Jul 1, 2015 should solve this:
* Added default for patterns_ini
* Added optional parameter output_handler when loaded as a module
* Renamed ioc-parser.py to iocp.py

**Comment by threatlead** [comment]
Thanks!
