### ISSUE TITLE
error   'ascii' codec can't encode character u'\u0160' in position 24: ordinal not in range(128)

### ISSUE THREAD

**Issue by r3comp1le** [armbues/ioc-parser#4]
http://www.trendmicro.co.uk/media/wp/operation-arid-viper-whitepaper-en.pdf

**Comment by buffer** [comment]
I confirm the issue but just with Python 2. I spent some time porting the code to Python 3 a few days ago and the issue does not exist under Python 3.

**Comment by armbues** [comment]
This is an error related to PDF parsing with the pypdf2 library using Python 2. With the support of pdfminer there is an alternative that seems to be more robust in parsing PDF reports, e.g. the report mentioned is parsed w/o errors.
